services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:   
      - back
    container_name: voluntarios-front
    env_file:
      - ./front/.env.production
   

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    entrypoint: "node ./build/index.js"
    container_name: voluntarios-back
    env_file:
      - ./back/.env
    restart: on-failure
  
   

  
